/*
* generated by Xtext
*/
package org.summer.xaml.core;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XAMLStandaloneSetup extends XAMLStandaloneSetupGenerated{

	public static void doSetup() {
		new XAMLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

