/*
 * generated by Xtext
 */
package org.summer.dsl.xtype.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.summer.dsl.xtype.ui.internal.XtypeActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XtypeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XtypeActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XtypeActivator.getInstance().getInjector(XtypeActivator.ORG_SUMMER_DSL_XTYPE_XTYPE);
	}
	
}
