/*
 * generated by Xtext
 */
package org.summer.dsl.ui.codetemplates;

import org.eclipse.xtext.conversion.impl.STRINGValueConverter;
import org.eclipse.xtext.parser.antlr.IPartialParsingHelper;
import org.summer.dsl.ui.codetemplates.conversion.SingleQuotedStringConverter;
import org.summer.dsl.ui.codetemplates.parser.CodetemplatesPartialParsingHelper;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SingleCodetemplateRuntimeModule extends org.summer.dsl.ui.codetemplates.AbstractSingleCodetemplateRuntimeModule {

	public Class<? extends STRINGValueConverter> bindSTRINGValueConverter() {
		return SingleQuotedStringConverter.class;
	}
	
	@Override
	public Class<? extends IPartialParsingHelper> bindIPartialParserHelper() {
		return CodetemplatesPartialParsingHelper.class;
	}
	
}
