/*
* generated by Xtext
*/
package org.summer.dsl.ui.codetemplates.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractCodetemplatesJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.summer.dsl.ui.codetemplates.templates.TemplatesPackage.eINSTANCE);
		return result;
	}

}
