/*
 * generated by Xtext
 */
package org.summer.dsl.xannotation.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XbaseWithAnnotationsUiModule extends org.summer.dsl.xannotation.ui.AbstractXbaseWithAnnotationsUiModule {
	public XbaseWithAnnotationsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
