/*
 * generated by Xtext
 */
package org.summer.dsl.xbase.ui;

import org.eclipse.jface.viewers.ILabelProvider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.copyqualifiedname.CopyQualifiedNameService;
import org.eclipse.xtext.ui.editor.hover.html.IEObjectHoverDocumentationProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.resource.ResourceServiceDescriptionLabelProvider;
import org.eclipse.xtext.validation.IssueSeveritiesProvider;
import org.summer.dsl.xbase.ui.editor.copyqualifiedname.XbaseCopyQualifiedNameService;
import org.summer.dsl.xbase.ui.highlighting.XbaseHighlightingConfiguration;
import org.summer.dsl.xbase.ui.hover.XbaseHoverDocumentationProvider;
import org.summer.dsl.xbase.ui.labeling.XbaseDescriptionLabelProvider;
import org.summer.dsl.xbase.ui.labeling.XbaseLabelProvider;
import org.summer.dsl.xbase.ui.validation.XbaseIssueSeveritiesProvider;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XbaseUiModule extends org.summer.dsl.xbase.ui.AbstractXbaseUiModule {

	public XbaseUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return XbaseHighlightingConfiguration.class;
	}
	
	@Override
	public Class<? extends IEObjectHoverDocumentationProvider> bindIEObjectHoverDocumentationProvider(){
		return XbaseHoverDocumentationProvider.class;
	}

	public Class<? extends IssueSeveritiesProvider> bindIssueSeverityServiceProvider() {
		return XbaseIssueSeveritiesProvider.class;
	}
	
	@Override
	public Class<? extends ILabelProvider> bindILabelProvider() {
		return XbaseLabelProvider.class;
	}

	@Override
	public void configureResourceUIServiceLabelProvider(Binder binder) {
		binder.bind(ILabelProvider.class).annotatedWith(ResourceServiceDescriptionLabelProvider.class).to(XbaseDescriptionLabelProvider.class);
	}
	
	@Override
	public Class<? extends CopyQualifiedNameService> bindCopyQualifiedNameService() {
		return XbaseCopyQualifiedNameService.class;
	}
	
}
