/*
* generated by Xtext
*/
package org.summer.dsl.xtype.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.summer.dsl.xtype.services.XtypeGrammarAccess;

public class XtypeParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XtypeGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.summer.dsl.xtype.parser.antlr.internal.InternalXtypeParser createParser(XtextTokenStream stream) {
		return new org.summer.dsl.xtype.parser.antlr.internal.InternalXtypeParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "JvmTypeReference";
	}
	
	public XtypeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XtypeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
