/*
* generated by Xtext
*/
package org.summer.dsl.xtype.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class XtypeAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/summer/dsl/xtype/parser/antlr/internal/InternalXtype.tokens");
	}
}
