/*
 * generated by Xtext
 */
package org.summer.xaml.core.ui.contentassist

import org.summer.xaml.core.ui.contentassist.AbstractXAMLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class XAMLProposalProvider extends AbstractXAMLProposalProvider {
}
