/*
* generated by Xtext
*/
package org.summer.dsl.xtype;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XtypeStandaloneSetup extends XtypeStandaloneSetupGenerated{

	public static void doSetup() {
		new XtypeStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

