/*
 * generated by Xtext
 */
package org.summer.xaml.core.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XAMLUiModule extends org.summer.xaml.core.ui.AbstractXAMLUiModule {
	public XAMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
